---
ipsec:
  private:
    path: /etc/ipsec.d/private
    ca_key: ca-key.pem
    server_key: server-key.pem

  cacerts:
    path: /etc/ipsec.d/cacerts
    ca_cert:
      filename: ca-cert.pem
      common_name: VPN Test Root CA

  certs:
    path: /etc/ipsec.d/certs
    server_cert:
      filename: server-cert.pem
      common_name: "{{ domain_name }}"
